name: distiller-env
channels:
    - conda-forge               
    - defaults                  
    - bioconda                  
    - golobor
dependencies:
    - python=3.6
    - parallel
    - pbgzip
    - samtools>=1.4
    - sra-tools>=2.8.1
    - fastqc
    - bwa==0.7.15
    - setuptools 
    - pip
    - cython 
    - numpy 
    - dask
    - nose 
    - pairix
    - pip:
        - cooler>=0.7.1
        - git+https://github.com/sergpolly/pairsamtools@merge_options_expansion
        - toolz
